{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
data:
  application.properties: |
    {{- range $key, $value := .Values.configmap.applicationProperties }}
    {{ $key }}={{ $value }}
    {{- end }}
{{- end }}
